name: Claude PR Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-code-action:
    if: |
      (
        (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
        (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
        (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
        (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
      )
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Check if user is collaborator
        id: check-collaborator
        run: |
          # Check if user has write permissions or higher (collaborator, maintainer, admin)
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission")
          permission=$(echo "$response" | jq -r '.permission // "none"')
          
          if [[ "$permission" == "write" || "$permission" == "maintain" || "$permission" == "admin" ]]; then
            echo "is_collaborator=true" >> $GITHUB_OUTPUT
            echo "✅ User ${{ github.actor }} is a collaborator with $permission permission"
          else
            echo "is_collaborator=false" >> $GITHUB_OUTPUT
            echo "❌ User ${{ github.actor }} is not a collaborator (permission: $permission)"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        if: steps.check-collaborator.outputs.is_collaborator == 'true'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude PR Action
        if: steps.check-collaborator.outputs.is_collaborator == 'true'
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        env:
          ANTHROPIC_BASE_URL: ${{ secrets.ANTHROPIC_BASE_URL }}
          ANTHROPIC_AUTH_TOKEN: ${{ secrets.ANTHROPIC_AUTH_TOKEN }}
          DISABLE_NON_ESSENTIAL_MODEL_CALLS: 1
          timeout_minutes: "60"
